# from GitHub
collections:
  # Install a collection from Ansible Galaxy.
  - name: theforeman.foreman
    src: git+https://github.com/zer0glitch/galaxy.git 
#    type: git
#  - name: galaxy
#    src: git+https://github.com/zer0glitch/galaxy.git 
#    type: git
#    #version: main
#  - name: https://github.com/zer0glitch/galaxy.git 
#    type: git
#    path: roles


