# from GitHub
collections:
  # Install a collection from Ansible Galaxy.
  - name: theforeman.foreman
    source: git+https://github.com/zer0glitch/galaxy.git 
    type: git
#  - name: 
#    type: git
#    version: main
