- hosts: rh7-ans-srv01.matrix.lab ansible_connection=local
  tasks: 

  - name: "Create a host with build context"
    become: awx
    theforeman.foreman.host:
      username: "{{ admin_user }}"
      password: "{{ admin_password }}"
      server_url: "https://rh7-sat6-srv01.matrix.lab/"
      name: "dev_database.matrix.lab"
      hostgroup: eucom_dev_database
      ip: 10.10.10.59
      validate_certs: False
      compute_attributes:
        start: "1"
      build: true
      state: present
