---

- hosts: foreman_eucom_rhel_8
  tasks:

  - name: touch file
    file:
      path: /tmp/me
      state: touch
      mode: 0700

  - name: import rotle example
    import_role: 
      name: ansible-role-php
